language: python
python:
  - "3.4"

install:
  - pip install -r requirements.txt -q
  - npm install -g less

script:
  - git clone --depth 1 --quiet https://${GH_TOKEN}@github.com/channprj/channprj.github.io.git output
  - pelican -s pelicanconf.py

after_success:
  - cd output
  - git add -f .
  - git commit -a -m "Contents updated from github using travis-ci."
  - git push https://${GH_TOKEN}@github.com/channprj/channprj.github.io.git master --quiet

branches:
  only:
    - master
